CampLending/Controllers/BiodataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CampRepo;
using Camp.DataModel;
using System.Web.Mvc;

namespace CampLending.Controllers
{
    public class BiodataController : Controller
    {
        // GET: Biodata
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            List<Biodata> list = BiodataRepo.All();
            list = list.Where(a => a.is_deleted == false).ToList();
            return PartialView("_List", list);
        }

        public ActionResult Create()
        {
            return PartialView("_Create", new Biodata());
        }
        [HttpPost]
        public ActionResult Create(Biodata product)
        {
            RespondResult result = BiodataRepo.Update(product);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Delete(long id)
        {
            return PartialView("_Delete", BiodataRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(Biodata model)
        {
            RespondResult result = BiodataRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

CampLending/Views/Biodata/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <input type="button" id="btn-create" name="btn-create" class="btn btn-default" value="Create" />
    </div>
    <div class="panel-body"></div>
    <div id="product-list"> Loading </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" id="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                <h4 class="modal-title">Title Here</h4>
            </div>
            <div class="modal-body"><p>the body</p></div>
        </div>

    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });
        $('#btn-create').click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Biodata")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("New Member");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });
        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "Biodata")',
                type: 'get',
                success: function (result) {
                    $("#product-list").html(result);
                }
            });
        }
    </script>
}

CampLending/Views/Biodata/_Create.cshtml
@model Camp.DataModel.Biodata

@using (Html.BeginForm("Create", "Biodata", FormMethod.Post, new { id = "form-create", name = "form-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.fullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2"><b>Alamat</b></div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.pob, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.pob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dob, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dob, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#form-create").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert("Save successful!");
                    GetList();
                    $(".modal").modal("hide");
                }
            }
        });
        return false;
    });
</script>

CampLending/Views/Biodata/_Delete.cshtml
@model CampViewModel.BiodataViewModel

<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm("Delete", "Biodata", FormMethod.Post, new { id = "form-delete", name = "form-delete" }))
{
    <div>
        <h4>Biodata</h4>
        <hr />
        <dl class="dl-horizontal">
            @Html.HiddenFor(model => model.id)
            <dt>
                @Html.DisplayNameFor(model => model.fullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.fullName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
}
<script type="text/javascript">
        $("#form-delete").submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    if (result.success) {
                        alert("Save successful!");
                        $(".modal").modal("hide");
                        GetList();
                    } else {
                        alert("Error! " + result.message);
                    }
                }
            });
            return false;
        });
</script>

CampLending/Views/Biodata/_List.cshtml
@model IEnumerable<Camp.DataModel.Biodata>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.create_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.create_on)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.modified_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.modified_on)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.pob)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dob)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.position)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.create_by)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.create_on)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.modified_by)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.modified_on)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.position)
            </td>
            <td>
                <div class="btn-group btn-group-sm">
                    <button type="button" class="btn btn-warning btn-edit" data-id="@item.id" title="Edit">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </button>
                    <button type="button" class="btn btn-danger btn-delete" data-id="@item.id" title="Delete">
                        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                    </button>
                </div>
            </td>
        </tr>
    }

</table>
<script type="text/javascript">

    $(".btn-edit").click(function () {
        $.ajax({
            url: '@Url.Action("Edit","Biodata")',
            type: 'get',
            data: {id: $(this).attr("data-id")},
            success: function (result) {
                $(".modal-title").html("Edit");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });

    $(".btn-delete").click(function () {
        $.ajax({
            url: '@Url.Action("Delete","Biodata")',
            type: 'get',
            data: {id: $(this).attr("data-id")},
            success: function (result) {
                $(".modal-title").html("Delete");
                $(".modal-body").html(result);
                $(".modal").modal("show");
            }
        });
    });
</script>