CampLending/Controllers/ReceiptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CampRepo;
using Camp.DataModel;
using System.Web.Mvc;

namespace CampLending.Controllers
{
    public class ReceiptController : Controller
    {
        // GET: Receipt
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            return PartialView("_List", ReceiptRepo.All());
        }

        public ActionResult Create()
        {
            return PartialView("_Create", new ReceiptHead());
        }
        [HttpPost]
        public ActionResult Create(ReceiptHead product)
        {
            RespondResult result = ReceiptRepo.Update(product);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

CampLending/Views/Receipt/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-primary">
    <div class="panel-heading">
        <input type="button" id="btn-create" name="btn-create" class="btn btn-default" value="Create" />
    </div>
    <div class="panel-body"></div>
    <div id="product-list"> Loading </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content" id="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
                <h4 class="modal-title">Title Here</h4>
            </div>
            <div class="modal-body"><p>the body</p></div>
        </div>

    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });
        $('#btn-create').click(function () {
            $.ajax({
                url: '@Url.Action("Create", "Receipt")',
                type: 'get',
                success: function (result) {
                    $(".modal-tittle").html("New Product");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });
        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "Receipt")',
                type: 'get',
                success: function (result) {
                    $("#product-list").html(result);
                }
            });
        }
    </script>
}

CampLending/Views/Receipt/_Create.cshtml
@model Camp.DataModel.ReceiptHead

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ReceiptHead</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.biodataId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.biodataId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.biodataId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.borrowTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.borrowTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.borrowTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.status)
                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.returnTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.returnTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.returnTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CampLending/Views/Receipt/_List.cshtml
@model IEnumerable<Camp.DataModel.ReceiptHead>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.create_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.create_on)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.modified_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.modified_on)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.deleted_by)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.deleted_on)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.is_deleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.biodataId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.borrowTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.returnTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.create_by)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.create_on)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.modified_by)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.modified_on)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.deleted_by)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.deleted_on)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.is_deleted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.biodataId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.borrowTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.returnTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>